### ISSUE TITLE
Uninstaller for this module

### ISSUE THREAD

**Issue by bonbonboi** [Magisk-Modules-Repo/extendwifi#1]
Hi,

I have flashed this by mistake, I was not aware it's for OP phones, now my phone wouldn't boot, I need to uninstall to back to the original state, I can access recovery mode if needed. Thanks

**Comment by thomasvt1** [comment]
Hi,

Don't worry it's pretty easy to revert this.

First download "magisk mount" from https://forum.xda-developers.com/apps/magisk/collection-magisk-modules-t3445257

Then go to your recovery. Then enable adb sideload, or find another way to get the zip on your phone. (USB OTG for example)

Flash this file. And then go to the file viewer in your recovery (twrp has this under advanced)

Go to /Magisk and remove the folder.

If you'd like some visuals with this I'd suggest watching this video https://www.youtube.com/watch?v=PiJ_N7VxHVk

I hope this helps

**Comment by thomasvt1** [comment]
Since no reply has been sent - I see this as solved

**Comment by bonbonboi** [comment]
It's okay I got new experience by your reply. I admit I didn't wait for a reply I did hard reset to solve the problem maybe after some hours prior to posting my issue here. Anyway now I got a better understanding how magisk works.

**Comment by thomasvt1** [comment]
Justing pinging @bonbonboi to let you know this module *should* now work on your phone aswell :)

**Comment by bonbonboi** [comment]
I'll test. Thanks
