### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by gjf** [Magisk-Modules-Repo/extendwifi#2]
Looks not working on MIUI 9 (Android 7.1.2) with Magisk 16.0
getprop shows initial values with no changes.

I've tried to write the similar script - the only solution for me is to use post-fs-data.sh to properly run resetprop.

**Comment by gjf** [comment]
And looks like I found the source of the problem: you forgot to set `PROPFILE=true` in your config.sh same as me.

But anyway even after that your mod still does not change props - getprop returns initial results.

Too bad.

**Comment by thomasvt1** [comment]
Sorry for the late reply!

I just set PROPFILE=true for good measure.

I have the same issue with MIUI but I can't seem to fix it. Seems like MIUI just dislikes prop changes.
